version: '3.8'

services:
  php74:
    build:
      context: .
      dockerfile: Dockerfile.74
    ports:
    - 80:80
    volumes:
    - ./php:/var/www/html/

  php56:
    build:
      context: .
      dockerfile: Dockerfile.56
    ports:
    - 88:80
    volumes:
    - ./php:/var/www/html/

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
    - ./volumes/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password #example of a password

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
    - 8080:80